### ISSUE TITLE
Only sends to itself

### ISSUE THREAD

**Issue by mrgamer45** [Dropout1337/Discord-Mass-DM#2]
The bot only sends to itself. I know this because I had it say(under except) to await ctx.send(f'Could not send "{message}" to {user}') and when I do the command, all it says is "Could not send (my message) to (bot#number)"
![image](https://user-images.githubusercontent.com/72839119/99591328-a1cba380-29bc-11eb-9d61-7e189994e068.png)

**Comment by Pool800** [comment]
Most of dropouts programs are super flawed and have problems so I am not so suprised honestly

**Comment by mrgamer45** [comment]
lol @Pool800 ye I just decided to actually learn python and not follow this shit
