### ISSUE TITLE
[Suggestion] Add an option to scrape already existing servers and/or not dm people

### ISSUE THREAD

**Issue by wrefgtzweve** [dropout1337/Discord-Mass-DM#7]
Two small suggestions:

Adding an option to scrape already joined servers would be great.
Having it toggleable to not dm people, could make this tool useful for just scraping too.

These could be out of scope for this project which i understand, just thought it might be neat.

**Comment by hoemotion** [comment]
> Two small suggestions:
> 
> Adding an option to scrape already joined servers would be great. Having it toggleable to not dm people, could make this tool useful for just scraping too.
> 
> These could be out of scope for this project which i understand, just thought it might be neat.

bruh just use the discum example for scraping and you can still enter the server invite code of already joined servers.. it will still work

**Comment by wrefgtzweve** [comment]
Yeah that's what i did lol, just thought it could be neat to have that build into this.
