### ISSUE TITLE
This is interesting 

### ISSUE THREAD

**Issue by Pyreaus** [Dropout1337/Discord-Mass-DM#8]
Hey dude this could be incredibly helpful for me but I have some quick questions: 

 Does this still work? If yes, does this work on **any** discord server? 
 Does this have a recipient/DM limit? (is there a limit to the number of DMs I can send)
 How long does the script take to send a mass DM to, say, 5,000 member server? 
 Does it take longer to send the DM if there are more members?

If you could answer these questions I would be internally grateful and if my project works out (which your script will help with greatly) I will be making sure to pay my debts back to you  (send me your user I can add you on discord) 🙏

**Comment by logicguy1** [comment]
It does not work, sorry

**Comment by Pyreaus** [comment]
> 
> 
> It does not work, sorry

Thanks.
